/*
NOME: KAMILLY AMANCIO BATISTA - MATRICULA: 202202570397
NOME: VICTOR LUCAS DA ROCHA MAIA - MATRICULA: 202202579981
NOME: RUBENS FERREIRA BARBOZA - MATRICULA: 202202640948
*/

#include "miniwin.h"  //BIBLIOTECA GRAPHICS 
using namespace miniwin; //IMPORTA TODAS AS FUNÇÕES DO MINIWIN

int main() {
	
	vredimensiona(500, 500);//JANELA DO WINDOWS DIMENSÕES 
	float x, y, ux, uy; //GUARDA NÚMEROS REAIS  
	bool inicio = true, esq, dir; //DECLARA 3 VARIÁVEIS DO TIPO BOOLEANO
		
	int t = tecla();//ATRIBUI UM VALOR A T
	while (t != ESCAPE) {//INICIA UM LOOP
		if (raton(x, y)) {//VERIFICA SE O MOUSE ESTA SENDO USADO E ATRIBUI COORDENADAS AS VARIÁVEIS X E Y
			raton_botones(esq, dir);//DECLARA DUAS VARIÁVEIS AOS BOTÕES DO MOUSE
				if (esq || dir) {//VERIFICA SE ALGUNS BOTÕES DO MOUSE FORAM PRECIONADOS 
					if (inicio) {//VERIFICA SE O PROGRAMA FOI INICIADO  
						ux = x, uy = y;//ARMAZENAS A COORDENADAS DO MOUSE NAS VARIÁVEIS UX E UY
						inicio = false;//ALTERA A VARIÁVEL INICIO PARA FIM
					}
					if (raton_boton_izq()) {//VERIFICA SE O BOTÃO ESQUERDO FOI PRECIONADO
					color(AMARILLO);//SE O BOTÃO ESQUERDO FOR PRECIONADO DEFINE A COR AMARELA
					} else if (raton_boton_der()) {//VERIFICA SE O BOTÃO DIREITO FOI PRECIONADO
						color(ROJO);//SE O BOTÃO DIREITO FOR PRECIONADO DEFINE A COR ROXA
					}
	linea(ux, uy, x, y);//DESENHA UMA LINHA NAS COORDENADAS UX, UY, X, Y
	ux = x, uy = y;//ATUALIZA AS COORDENADAS ARMAZENADAS EM UX E UY COM AS COORDENADAS ATUAIS DO MOUSE
	refresca();//ATUALIZA A JANELA DE DESENHO
} else {//SE NENHUM BOTÃO FOR PRECIONADO NÃO É EXECUTADO NENHUMA FUNÇÃO
		inicio = true;//SE NENHUMA TECLA FOR PRECIONADA, A VARIAVEL INICIO É DEFINIDA COMO VERDADEIRA
	}
		}	
		t = tecla();//ESPERA O USUARIO PRECIONAR A TECLA E ARMAZENAR O VALOR NA VARIAVEL
}//TERMINA O LOOP
	vcierra(); //FECHA A JANELA
return 0;//ENCERRA A EXECUÇÃO
}
